/*
 * Created by SharpDevelop.
 * User: dao
 * Date: 23.02.2009
 * Time: 15:43
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */

using System;
using System.Collections;
using System.Collections.Specialized;

namespace ETRTranslator
{
	/// <summary>
	/// Description of MorfologRusTab.
	/// </summary>
	partial class MorfologRus
	{
		void AnalyzeGramTab(ref Slovo slovo,string flex,string gr)
		{
			string gramstring = rusgramtab[flex]+","+rusgramtab[gr]+",";
			
		//	System.Windows.Forms.MessageBox.Show(flex+" - "+gr);
		//	System.Windows.Forms.MessageBox.Show(gramstring);
			
			//Анализируем часть речи
			 
			if(gramstring.IndexOf("С,")!=-1)
				slovo.chastRechi = ChastRechi.Suschestvitelnoe;
			else if (gramstring.IndexOf("П,")!=-1)
				slovo.chastRechi = ChastRechi.Prilagatelnoe;
			else if (gramstring.IndexOf("МС,")!=-1)
				slovo.chastRechi = ChastRechi.Mestoimenie;
			else if (gramstring.IndexOf("Г,")!=-1)
				slovo.chastRechi = ChastRechi.Glagol;
			else if (gramstring.IndexOf("ПРИЧАСТИЕ,")!=-1)
				slovo.chastRechi = ChastRechi.Prichastie;
			else if (gramstring.IndexOf("ДЕЕПРИЧАСТИЕ,")!=-1)
				slovo.chastRechi = ChastRechi.Deeprichastie;
			else if (gramstring.IndexOf("ИНФИНИТИВ,")!=-1)
			{
				slovo.chastRechi = ChastRechi.Glagol;
				slovo.naklonenie = Naklonenie.Infinitiv;
			}
			else if (gramstring.IndexOf("ЧИСЛ,")!=-1)
				slovo.chastRechi = ChastRechi.Chislitelnoe;
			else if (gramstring.IndexOf("ЧИСЛ-П,")!=-1)
				slovo.chastRechi = ChastRechi.ChislitelnoePoryadkovoe;
			else if (gramstring.IndexOf("Н,")!=-1)
				slovo.chastRechi = ChastRechi.Narechie;
			else if (gramstring.IndexOf("ПРЕДК,")!=-1)
			{
				slovo.chastRechi = ChastRechi.Prilagatelnoe;
				slovo.ruSlovo.ruRod = RuRod.Srednij;
				slovo.ruSlovo.ruForma  = RuForma.Kratkaya;
			}
			else if (gramstring.IndexOf("ПРЕДЛ,")!=-1)
				slovo.chastRechi = ChastRechi.Predlog;
			else if (gramstring.IndexOf("СОЮЗ,")!=-1)
				slovo.chastRechi = ChastRechi.Souz;
			else if (gramstring.IndexOf("МЕЖД,")!=-1)
				slovo.chastRechi = ChastRechi.Mezhdometie;
			else if (gramstring.IndexOf("ЧАСТ,")!=-1)
				slovo.chastRechi = ChastRechi.Chastica;
			else if (gramstring.IndexOf("ВВОДН,")!=-1)
				slovo.chastRechi = ChastRechi.Mezhdometie;
			else if (gramstring.IndexOf("КР_ПРИЛ,")!=-1)
			{
				slovo.chastRechi = ChastRechi.Prilagatelnoe;
				slovo.ruSlovo.ruForma = RuForma.Kratkaya;
			}
			else if (gramstring.IndexOf("КР_ПРИЧАСТИЕ,")!=-1)
			{
				slovo.chastRechi = ChastRechi.Prichastie;
				slovo.ruSlovo.ruForma = RuForma.Kratkaya;
			}
			
			//Анализ граммем
			
			if(gramstring.IndexOf("мр,")!=-1)
				slovo.ruSlovo.ruRod = RuRod.Muzhskoj;
			else if(gramstring.IndexOf("жр,")!=-1)
				slovo.ruSlovo.ruRod = RuRod.Zhenskij;
			else if(gramstring.IndexOf("ср,")!=-1)
				slovo.ruSlovo.ruRod = RuRod.Srednij;
			
			if(gramstring.IndexOf("од,")!=-1)
				slovo.odushevlennost = Odushevlennost.Odushevlennoe;
			else if(gramstring.IndexOf("но,")!=-1)
				slovo.odushevlennost = Odushevlennost.Neodushevlennoe;
			
			if(gramstring.IndexOf("ед,")!=-1)
				slovo.ruSlovo.ruChislo = RuChislo.Edinstvennoe;
			else if(gramstring.IndexOf("мн,")!=-1)
				slovo.ruSlovo.ruChislo = RuChislo.Mnozhestvennoe;
			
			if(gramstring.IndexOf("им,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Imenitelniy;
			else if(gramstring.IndexOf("рд,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Roditelniy;
			else if(gramstring.IndexOf("дт,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Datelniy;
			else if(gramstring.IndexOf("вн,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Vinitelniy;
			else if(gramstring.IndexOf("тв,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Tvoritelniy;
			else if(gramstring.IndexOf("пр,")!=-1)
				slovo.ruSlovo.ruPadezh = RuPadezh.Predlozhniy;
			
			if(gramstring.IndexOf("св,")!=-1)
				slovo.ruSlovo.ruVid = RuVid.Sovershenniy;
			else if(gramstring.IndexOf("нс,")!=-1)
				slovo.ruSlovo.ruVid = RuVid.Nesovershenniy;
			
			if(gramstring.IndexOf("пе,")!=-1)
				slovo.ruSlovo.ruPerehodnost = RuPerehodnost.Perehodniy;
			else if(gramstring.IndexOf("нп,")!=-1)
				slovo.ruSlovo.ruPerehodnost = RuPerehodnost.Neperehodniy;
			
			if(gramstring.IndexOf("дст,")!=-1)
				slovo.zalog = Zalog.Dejstvitekniy;
			else if(gramstring.IndexOf("стр,")!=-1)
				slovo.zalog = Zalog.Stradatelniy;
			
			if(gramstring.IndexOf("нст,")!=-1)
				slovo.vremya = Vremya.Nastoyaschee;
			else if(gramstring.IndexOf("прш,")!=-1)
				slovo.vremya = Vremya.Proshedshee;
			else if(gramstring.IndexOf("буд,")!=-1)
				slovo.vremya = Vremya.Buduschee;
			
			if(gramstring.IndexOf("пвл,")!=-1)
				slovo.naklonenie = Naklonenie.Povelitelnoe;
			
			if(gramstring.IndexOf("1л,")!=-1)
				slovo.ruSlovo.ruLico = RuLico.Pervoe;
			else if(gramstring.IndexOf("2л,")!=-1)
				slovo.ruSlovo.ruLico = RuLico.Vtoroe;
			else if(gramstring.IndexOf("3л,")!=-1)
				slovo.ruSlovo.ruLico = RuLico.Tretie;
			
			if(gramstring.IndexOf("кр,")!=-1)
				slovo.ruSlovo.ruForma = RuForma.Kratkaya;
			
			if(gramstring.IndexOf("кр,")!=-1)
				slovo.ruSlovo.ruForma = RuForma.Kratkaya;
			
			if(gramstring.IndexOf("сравн,")!=-1)
				slovo.stepenSravneniya = StepenSravneniya.Bolee;
			
			if(gramstring.IndexOf("безл,")!=-1)
				slovo.ruSlovo.ruLico = RuLico.Bezlichnoe;
			
		}
		
		Slovo PostAnalyzePadezh(Predlozhenie pr,int place)
		{
			Slovo s = pr[place];
			int pl = place-1;
			
			if(pl>=0)
			{
				Slovo prev = (Slovo)pr[pl];
						
				while(pl>0&&(prev.chastRechi == ChastRechi.Prilagatelnoe || prev.chastRechi == ChastRechi.ChislitelnoePoryadkovoe || prev.chastRechi == ChastRechi.Chislitelnoe))
				{
					pl--;
					prev = (Slovo)pr[pl];
				}
				
				if(prev.chastRechi == ChastRechi.Predlog)
				{
				//	Slovo prev = (Slovo)pr[place-1];
									
					if(prev.rSlovo == "к")
						s.ruSlovo.ruPadezh = RuPadezh.Datelniy;
					else if(prev.rSlovo == "по")
						s.ruSlovo.ruPadezh = RuPadezh.Datelniy;
					else if(prev.rSlovo == "без")
						s.ruSlovo.ruPadezh = RuPadezh.Roditelniy;
					else if(prev.rSlovo == "о")
						s.ruSlovo.ruPadezh = RuPadezh.Predlozhniy;
				/*	else if(prev.rSlovo == "с")
						s.ruSlovo.ruPadezh = RuPadezh.Tvoritelniy;					*/
				}
			}
			
			return s;
		}
		
		Hashtable rusgramtab = new Hashtable();
		void InitializeGramTab()
		{
			rusgramtab["аа"] = "A,С,мр,ед,им";
			rusgramtab["аб"] = "A,С,мр,ед,рд";
			rusgramtab["Эф"] = "A,С,мр,ед,рд,2";
			rusgramtab["ав"] = "A,С,мр,ед,дт";
			rusgramtab["аг"] = "A,С,мр,ед,вн";
			rusgramtab["ад"] = "A,С,мр,ед,тв";
			rusgramtab["ае"] = "A,С,мр,ед,пр";
			rusgramtab["Эх"] = "A,С,мр,ед,пр,2";
			rusgramtab["ас"] = "A,С,мр,ед,зв,";
			rusgramtab["аж"] = "A,С,мр,мн,им";
			rusgramtab["аз"] = "A,С,мр,мн,рд";
			rusgramtab["аи"] = "A,С,мр,мн,дт";
			rusgramtab["ай"] = "A,С,мр,мн,вн";
			rusgramtab["ак"] = "A,С,мр,мн,тв";
			rusgramtab["ал"] = "A,С,мр,мн,пр";
			rusgramtab["ам"] = "B,С,мр,0";
			rusgramtab["ан"] = "B,С,мр,ед,0";
			rusgramtab["Юо"] = "A,С,мр,ед,им,разг,";
			rusgramtab["Юп"] = "A,С,мр,ед,рд,разг,";
			rusgramtab["Юр"] = "A,С,мр,ед,дт,разг,";
			rusgramtab["Юс"] = "A,С,мр,ед,вн,разг,";
			rusgramtab["Ют"] = "A,С,мр,ед,тв,разг,";
			rusgramtab["Юф"] = "A,С,мр,ед,пр,разг,";
			rusgramtab["Юх"] = "A,С,мр,ед,зв,разг,";
			rusgramtab["Яб"] = "A,С,мр,мн,им,разг,";
			rusgramtab["Яа"] = "A,С,мр,мн,рд,разг";
			rusgramtab["Яв"] = "A,С,мр,мн,дт,разг";
			rusgramtab["Яг"] = "A,С,мр,мн,вн,разг";
			rusgramtab["Яд"] = "A,С,мр,мн,тв,разг";
			rusgramtab["Яж"] = "A,С,мр,мн,пр,разг";
			rusgramtab["го"] = "A,С,мр,ед,им,арх,";
			rusgramtab["гп"] = "A,С,мр,ед,рд,арх,";
			rusgramtab["гр"] = "A,С,мр,ед,дт,арх,";
			rusgramtab["гс"] = "A,С,мр,ед,вн,арх,";
			rusgramtab["гт"] = "A,С,мр,ед,тв,арх,";
			rusgramtab["гу"] = "A,С,мр,ед,пр,арх,";
			rusgramtab["гф"] = "A,С,мр,мн,им,арх,";
			rusgramtab["гх"] = "A,С,мр,мн,рд,арх";
			rusgramtab["гц"] = "A,С,мр,мн,дт,арх";
			rusgramtab["гч"] = "A,С,мр,мн,вн,арх";
			rusgramtab["гш"] = "A,С,мр,мн,тв,арх";
			rusgramtab["гщ"] = "A,С,мр,мн,пр,арх";
			rusgramtab["ва"] = "E,С,мр-жр,ед,им";
			rusgramtab["вб"] = "E,С,мр-жр,ед,рд";
			rusgramtab["вв"] = "E,С,мр-жр,ед,дт";
			rusgramtab["вг"] = "E,С,мр-жр,ед,вн";
			rusgramtab["вд"] = "E,С,мр-жр,ед,тв";
			rusgramtab["ве"] = "E,С,мр-жр,ед,пр";
			rusgramtab["вж"] = "E,С,мр-жр,мн,им";
			rusgramtab["вз"] = "E,С,мр-жр,мн,рд";
			rusgramtab["ви"] = "E,С,мр-жр,мн,дт";
			rusgramtab["вй"] = "E,С,мр-жр,мн,вн";
			rusgramtab["вк"] = "E,С,мр-жр,мн,тв";
			rusgramtab["вл"] = "E,С,мр-жр,мн,пр";
			rusgramtab["вм"] = "F,С,мр-жр,0";
			rusgramtab["вн"] = "F,С,мр-жр,ед,0";
			rusgramtab["во"] = "E,С,арх,мр-жр,ед,им";
			rusgramtab["вп"] = "E,С,арх,мр-жр,ед,рд";
			rusgramtab["вр"] = "E,С,арх,мр-жр,ед,дт";
			rusgramtab["вс"] = "E,С,арх,мр-жр,ед,вн";
			rusgramtab["вт"] = "E,С,арх,мр-жр,ед,тв";
			rusgramtab["ву"] = "E,С,арх,мр-жр,ед,пр";
			rusgramtab["вф"] = "E,С,арх,мр-жр,мн,им";
			rusgramtab["вх"] = "E,С,арх,мр-жр,мн,рд";
			rusgramtab["вц"] = "E,С,арх,мр-жр,мн,дт";
			rusgramtab["вч"] = "E,С,арх,мр-жр,мн,вн";
			rusgramtab["вш"] = "E,С,арх,мр-жр,мн,тв";
			rusgramtab["вщ"] = "E,С,арх,мр-жр,мн,пр";
			rusgramtab["га"] = "G,С,жр,ед,им";
			rusgramtab["гб"] = "G,С,жр,ед,рд";
			rusgramtab["гв"] = "G,С,жр,ед,дт";
			rusgramtab["гг"] = "G,С,жр,ед,вн";
			rusgramtab["гд"] = "G,С,жр,ед,тв";
			rusgramtab["ге"] = "G,С,жр,ед,пр";
			rusgramtab["Эч"] = "G,С,жр,ед,пр,2";
			rusgramtab["Йш"] = "G,С,жр,ед,зв";
			rusgramtab["гж"] = "G,С,жр,мн,им";
			rusgramtab["гз"] = "G,С,жр,мн,рд";
			rusgramtab["ги"] = "G,С,жр,мн,дт";
			rusgramtab["гй"] = "G,С,жр,мн,вн";
			rusgramtab["гк"] = "G,С,жр,мн,тв";
			rusgramtab["гл"] = "G,С,жр,мн,пр";
			rusgramtab["гм"] = "H,С,жр,0";
			rusgramtab["гн"] = "H,С,жр,ед,0";
			rusgramtab["Йа"] = "G,С,арх,жр,ед,им";
			rusgramtab["Йб"] = "G,С,арх,жр,ед,рд";
			rusgramtab["Йв"] = "G,С,арх,жр,ед,дт";
			rusgramtab["Йг"] = "G,С,арх,жр,ед,вн";
			rusgramtab["Йд"] = "G,С,арх,жр,ед,тв";
			rusgramtab["Йе"] = "G,С,арх,жр,ед,пр";
			rusgramtab["Йж"] = "G,С,арх,жр,мн,им";
			rusgramtab["Йз"] = "G,С,арх,жр,мн,рд";
			rusgramtab["Йи"] = "G,С,арх,жр,мн,дт";
			rusgramtab["Йй"] = "G,С,арх,жр,мн,вн";
			rusgramtab["Йк"] = "G,С,арх,жр,мн,тв";
			rusgramtab["Йл"] = "G,С,арх,жр,мн,пр";
			rusgramtab["Йм"] = "G,С,разг,жр,ед,им";
			rusgramtab["Йн"] = "G,С,разг,жр,ед,рд";
			rusgramtab["Йо"] = "G,С,разг,жр,ед,дт";
			rusgramtab["Йп"] = "G,С,разг,жр,ед,вн";
			rusgramtab["Йр"] = "G,С,разг,жр,ед,тв";
			rusgramtab["Йс"] = "G,С,разг,жр,ед,пр";
			rusgramtab["Йт"] = "G,С,разг,жр,мн,им";
			rusgramtab["Йу"] = "G,С,разг,жр,мн,рд";
			rusgramtab["Йф"] = "G,С,разг,жр,мн,дт";
			rusgramtab["Йх"] = "G,С,разг,жр,мн,вн";
			rusgramtab["Йц"] = "G,С,разг,жр,мн,тв";
			rusgramtab["Йч"] = "G,С,разг,жр,мн,пр";
			rusgramtab["еа"] = "K,С,ср,ед,им";
			rusgramtab["еб"] = "K,С,ср,ед,рд";
			rusgramtab["ев"] = "K,С,ср,ед,дт";
			rusgramtab["ег"] = "K,С,ср,ед,вн";
			rusgramtab["ед"] = "K,С,ср,ед,тв";
			rusgramtab["ее"] = "K,С,ср,ед,пр";
			rusgramtab["еж"] = "K,С,ср,мн,им";
			rusgramtab["ез"] = "K,С,ср,мн,рд";
			rusgramtab["еи"] = "K,С,ср,мн,дт";
			rusgramtab["ей"] = "K,С,ср,мн,вн";
			rusgramtab["ек"] = "K,С,ср,мн,тв";
			rusgramtab["ел"] = "K,С,ср,мн,пр";
			rusgramtab["ем"] = "L,С,ср,0";
			rusgramtab["ен"] = "L,С,ср,ед,0";
			rusgramtab["Эя"] = "K,С,ср,ед,рд,аббр";
			rusgramtab["Яз"] = "K,С,разг,ср,ед,им";
			rusgramtab["Яи"] = "K,С,разг,ср,ед,рд";
			rusgramtab["Як"] = "K,С,разг,ср,ед,дт";
			rusgramtab["Ял"] = "K,С,разг,ср,ед,вн";
			rusgramtab["Ям"] = "K,С,разг,ср,ед,тв";
			rusgramtab["Ян"] = "K,С,разг,ср,ед,пр";
			rusgramtab["Яо"] = "K,С,разг,ср,мн,им";
			rusgramtab["Яп"] = "K,С,разг,ср,мн,рд";
			rusgramtab["Яр"] = "K,С,разг,ср,мн,дт";
			rusgramtab["Яс"] = "K,С,разг,ср,мн,вн";
			rusgramtab["Ят"] = "K,С,разг,ср,мн,тв";
			rusgramtab["Яу"] = "K,С,разг,ср,мн,пр";
			rusgramtab["иж"] = "Q,С,мн,мн,им";
			rusgramtab["из"] = "Q,С,мн,мн,рд";
			rusgramtab["ии"] = "Q,С,мн,мн,дт";
			rusgramtab["ий"] = "Q,С,мн,мн,вн";
			rusgramtab["ик"] = "Q,С,мн,мн,тв";
			rusgramtab["ил"] = "Q,С,мн,мн,пр";
			rusgramtab["им"] = "R,С,мн,0";
			rusgramtab["ао"] = "B,С,мр,аббр,0,";
			rusgramtab["ап"] = "B,С,мр,ед,аббр,0";
			rusgramtab["ат"] = "H,С,жр,аббр,0";
			rusgramtab["ау"] = "H,С,жр,ед,аббр,0";
			rusgramtab["ац"] = "H,С,ср,аббр,0";
			rusgramtab["ач"] = "H,С,ср,ед,аббр,0";
			rusgramtab["аъ"] = "R,С,мн,аббр,0";
			rusgramtab["бо"] = "C,С,мр,имя,ед,им";
			rusgramtab["бп"] = "C,С,мр,имя,ед,рд";
			rusgramtab["бр"] = "C,С,мр,имя,ед,дт";
			rusgramtab["бс"] = "C,С,мр,имя,ед,вн";
			rusgramtab["бт"] = "C,С,мр,имя,ед,тв";
			rusgramtab["бу"] = "C,С,мр,имя,ед,пр";
			rusgramtab["бь"] = "C,С,мр,имя,ед,зв,разг";
			rusgramtab["бф"] = "C,С,мр,имя,мн,им";
			rusgramtab["бх"] = "C,С,мр,имя,мн,рд";
			rusgramtab["бц"] = "C,С,мр,имя,мн,дт";
			rusgramtab["бч"] = "C,С,мр,имя,мн,вн";
			rusgramtab["бш"] = "C,С,мр,имя,мн,тв";
			rusgramtab["бщ"] = "C,С,мр,имя,мн,пр";
			rusgramtab["бН"] = "I,С,мр,имя,0";
			rusgramtab["вН"] = "E,С,мр-жр,имя,0";
			rusgramtab["вО"] = "E,С,мр-жр,имя,ед,им";
			rusgramtab["вП"] = "E,С,мр-жр,имя,ед,рд";
			rusgramtab["вР"] = "E,С,мр-жр,имя,ед,дт";
			rusgramtab["вС"] = "E,С,мр-жр,имя,ед,вн";
			rusgramtab["вТ"] = "E,С,мр-жр,имя,ед,тв";
			rusgramtab["вУ"] = "E,С,мр-жр,имя,ед,пр";
			rusgramtab["вЬ"] = "E,С,мр-жр,имя,ед,зв,разг";
			rusgramtab["вФ"] = "E,С,мр-жр,имя,мн,им";
			rusgramtab["вХ"] = "E,С,мр-жр,имя,мн,рд";
			rusgramtab["вЦ"] = "E,С,мр-жр,имя,мн,дт";
			rusgramtab["вЧ"] = "E,С,мр-жр,имя,мн,вн";
			rusgramtab["вШ"] = "E,С,мр-жр,имя,мн,тв";
			rusgramtab["вЩ"] = "E,С,мр-жр,имя,мн,пр";
			rusgramtab["до"] = "I,С,жр,имя,ед,им";
			rusgramtab["дп"] = "I,С,жр,имя,ед,рд";
			rusgramtab["др"] = "I,С,жр,имя,ед,дт";
			rusgramtab["дс"] = "I,С,жр,имя,ед,вн";
			rusgramtab["дт"] = "I,С,жр,имя,ед,тв";
			rusgramtab["ду"] = "I,С,жр,имя,ед,пр";
			rusgramtab["дь"] = "I,С,жр,имя,ед,зв,разг";
			rusgramtab["дф"] = "I,С,жр,имя,мн,им";
			rusgramtab["дх"] = "I,С,жр,имя,мн,рд";
			rusgramtab["дц"] = "I,С,жр,имя,мн,дт";
			rusgramtab["дч"] = "I,С,жр,имя,мн,вн";
			rusgramtab["дш"] = "I,С,жр,имя,мн,тв";
			rusgramtab["дщ"] = "I,С,жр,имя,мн,пр";
			rusgramtab["дН"] = "I,С,жр,имя,0";
			rusgramtab["Ра"] = "Q,С,мр,отч,ед,им,";
			rusgramtab["Рб"] = "Q,С,мр,отч,ед,рд,";
			rusgramtab["Рв"] = "Q,С,мр,отч,ед,дт,";
			rusgramtab["Рг"] = "Q,С,мр,отч,ед,вн,";
			rusgramtab["Рд"] = "Q,С,мр,отч,ед,тв,";
			rusgramtab["Ре"] = "Q,С,мр,отч,ед,пр,";
			rusgramtab["Рн"] = "Q,С,мр,отч,мн,им,";
			rusgramtab["Ро"] = "Q,С,мр,отч,мн,рд,";
			rusgramtab["Рп"] = "Q,С,мр,отч,мн,дт,";
			rusgramtab["Рр"] = "Q,С,мр,отч,мн,вн,";
			rusgramtab["Рс"] = "Q,С,мр,отч,мн,тв,";
			rusgramtab["Рт"] = "Q,С,мр,отч,мн,пр,";
			rusgramtab["Рж"] = "Q,С,жр,отч,ед,им,";
			rusgramtab["Рз"] = "Q,С,жр,отч,ед,рд,";
			rusgramtab["Ри"] = "Q,С,жр,отч,ед,дт,";
			rusgramtab["Рк"] = "Q,С,жр,отч,ед,вн,";
			rusgramtab["Рл"] = "Q,С,жр,отч,ед,тв,";
			rusgramtab["Рм"] = "Q,С,жр,отч,ед,пр,";
			rusgramtab["Ру"] = "Q,С,жр,отч,мн,им,";
			rusgramtab["Рф"] = "Q,С,жр,отч,мн,рд,";
			rusgramtab["Рх"] = "Q,С,жр,отч,мн,дт,";
			rusgramtab["Рц"] = "Q,С,жр,отч,мн,вн,";
			rusgramtab["Рч"] = "Q,С,жр,отч,мн,тв,";
			rusgramtab["Рш"] = "Q,С,жр,отч,мн,пр,";
			rusgramtab["Та"] = "Q,С,мр,отч,разг,ед,им,";
			rusgramtab["Тб"] = "Q,С,мр,отч,разг,ед,рд,";
			rusgramtab["Тв"] = "Q,С,мр,отч,разг,ед,дт,";
			rusgramtab["Тг"] = "Q,С,мр,отч,разг,ед,вн,";
			rusgramtab["Тд"] = "Q,С,мр,отч,разг,ед,тв,";
			rusgramtab["Те"] = "Q,С,мр,отч,разг,ед,пр,";
			rusgramtab["Тн"] = "Q,С,мр,отч,разг,мн,им,";
			rusgramtab["То"] = "Q,С,мр,отч,разг,мн,рд,";
			rusgramtab["Тп"] = "Q,С,мр,отч,разг,мн,дт,";
			rusgramtab["Тр"] = "Q,С,мр,отч,разг,мн,вн,";
			rusgramtab["Тс"] = "Q,С,мр,отч,разг,мн,тв,";
			rusgramtab["Тт"] = "Q,С,мр,отч,разг,мн,пр,";
			rusgramtab["Тж"] = "Q,С,жр,отч,разг,ед,им,";
			rusgramtab["Тз"] = "Q,С,жр,отч,разг,ед,рд,";
			rusgramtab["Ти"] = "Q,С,жр,отч,разг,ед,дт,";
			rusgramtab["Тк"] = "Q,С,жр,отч,разг,ед,вн,";
			rusgramtab["Тл"] = "Q,С,жр,отч,разг,ед,тв,";
			rusgramtab["Тм"] = "Q,С,жр,отч,разг,ед,пр,";
			rusgramtab["Ту"] = "Q,С,жр,отч,разг,мн,им,";
			rusgramtab["Тф"] = "Q,С,жр,отч,разг,мн,рд,";
			rusgramtab["Тх"] = "Q,С,жр,отч,разг,мн,дт,";
			rusgramtab["Тц"] = "Q,С,жр,отч,разг,мн,вн,";
			rusgramtab["Тч"] = "Q,С,жр,отч,разг,мн,тв,";
			rusgramtab["Тш"] = "Q,С,жр,отч,разг,мн,пр,";
			rusgramtab["йа"] = "Y,П,мр,ед,им,од,но";
			rusgramtab["йб"] = "Y,П,мр,ед,рд,од,но";
			rusgramtab["йв"] = "Y,П,мр,ед,дт,од,но";
			rusgramtab["йг"] = "Y,П,мр,ед,вн,од";
			rusgramtab["Рщ"] = "Y,П,мр,ед,вн,но";
			rusgramtab["йд"] = "Y,П,мр,ед,тв,од,но";
			rusgramtab["йе"] = "Y,П,мр,ед,пр,од,но";
			rusgramtab["йж"] = "Y,П,жр,ед,им,од,но";
			rusgramtab["йз"] = "Y,П,жр,ед,рд,од,но";
			rusgramtab["йи"] = "Y,П,жр,ед,дт,од,но";
			rusgramtab["йй"] = "Y,П,жр,ед,вн,од,но";
			rusgramtab["йк"] = "Y,П,жр,ед,тв,од,но";
			rusgramtab["йл"] = "Y,П,жр,ед,пр,од,но";
			rusgramtab["йм"] = "Y,П,ср,ед,им,од,но";
			rusgramtab["йн"] = "Y,П,ср,ед,рд,од,но";
			rusgramtab["йо"] = "Y,П,ср,ед,дт,од,но";
			rusgramtab["йп"] = "Y,П,ср,ед,вн,од,но";
			rusgramtab["йр"] = "Y,П,ср,ед,тв,од,но";
			rusgramtab["йс"] = "Y,П,ср,ед,пр,од,но";
			rusgramtab["йт"] = "Y,П,мн,им,од,но";
			rusgramtab["йу"] = "Y,П,мн,рд,од,но";
			rusgramtab["йф"] = "Y,П,мн,дт,од,но";
			rusgramtab["йх"] = "Y,П,мн,вн,од";
			rusgramtab["Рь"] = "Y,П,мн,вн,но";
			rusgramtab["йц"] = "Y,П,мн,тв,од,но";
			rusgramtab["йч"] = "Y,П,мн,пр,од,но";
			rusgramtab["йш"] = "Y,КР_ПРИЛ,мр,ед,од,но";
			rusgramtab["йщ"] = "Y,КР_ПРИЛ,жр,ед,од,но";
			rusgramtab["йы"] = "Y,КР_ПРИЛ,ср,ед,од,но";
			rusgramtab["йэ"] = "Y,КР_ПРИЛ,мн,од,но";
			rusgramtab["йю"] = "Y,П,сравн,од,но";
			rusgramtab["йъ"] = "Y,П,сравн,2,од,но";
			rusgramtab["йь"] = "Y,П,сравн,од,но,разг";
			rusgramtab["йя"] = "Z,П,0,од,но";
			rusgramtab["иа"] = "Y,П,прев,мр,ед,им,од,но";
			rusgramtab["иб"] = "Y,П,прев,мр,ед,рд,од,но";
			rusgramtab["ив"] = "Y,П,прев,мр,ед,дт,од,но";
			rusgramtab["иг"] = "Y,П,прев,мр,ед,вн,од";
			rusgramtab["ид"] = "Y,П,прев,мр,ед,вн,но";
			rusgramtab["ие"] = "Y,П,прев,мр,ед,тв,од,но";
			rusgramtab["Гб"] = "Y,П,прев,мр,ед,пр,од,но";
			rusgramtab["Гв"] = "Y,П,прев,жр,ед,им,од,но";
			rusgramtab["Гг"] = "Y,П,прев,жр,ед,рд,од,но";
			rusgramtab["Гд"] = "Y,П,прев,жр,ед,дт,од,но";
			rusgramtab["Ге"] = "Y,П,прев,жр,ед,вн,од,но";
			rusgramtab["Гж"] = "Y,П,прев,жр,ед,тв,од,но";
			rusgramtab["Гз"] = "Y,П,прев,жр,ед,пр,од,но";
			rusgramtab["ин"] = "Y,П,прев,ср,ед,им,од,но";
			rusgramtab["ио"] = "Y,П,прев,ср,ед,рд,од,но";
			rusgramtab["ип"] = "Y,П,прев,ср,ед,дт,од,но";
			rusgramtab["ир"] = "Y,П,прев,ср,ед,вн,од,но";
			rusgramtab["ис"] = "Y,П,прев,ср,ед,тв,од,но";
			rusgramtab["ит"] = "Y,П,прев,ср,ед,пр,од,но";
			rusgramtab["иу"] = "Y,П,прев,мн,им,од,но";
			rusgramtab["иф"] = "Y,П,прев,мн,рд,од,но";
			rusgramtab["их"] = "Y,П,прев,мн,дт,од,но";
			rusgramtab["иц"] = "Y,П,прев,мн,вн,од";
			rusgramtab["ич"] = "Y,П,прев,мн,вн,но";
			rusgramtab["иш"] = "Y,П,прев,мн,тв,од,но";
			rusgramtab["ищ"] = "Y,П,прев,мн,пр,од,но";
			rusgramtab["нр"] = "a,ИНФИНИТИВ,безл";
			rusgramtab["нс"] = "a,Г,безл,буд,";
			rusgramtab["нт"] = "a,Г,безл,прш";
			rusgramtab["ну"] = "a,Г,безл,нст";
			rusgramtab["ка"] = "a,ИНФИНИТИВ,дст";
			rusgramtab["кб"] = "a,Г,дст,нст,1л,ед";
			rusgramtab["кв"] = "a,Г,дст,нст,1л,мн";
			rusgramtab["кг"] = "a,Г,дст,нст,2л,ед";
			rusgramtab["кд"] = "a,Г,дст,нст,2л,мн";
			rusgramtab["ке"] = "a,Г,дст,нст,3л,ед";
			rusgramtab["кж"] = "a,Г,дст,нст,3л,мн";
			rusgramtab["кз"] = "a,Г,дст,прш,мр,ед";
			rusgramtab["ки"] = "a,Г,дст,прш,жр,ед";
			rusgramtab["кй"] = "a,Г,дст,прш,ср,ед";
			rusgramtab["кк"] = "a,Г,дст,прш,мн";
			rusgramtab["кп"] = "a,Г,дст,буд,1л,ед";
			rusgramtab["кр"] = "a,Г,дст,буд,1л,мн";
			rusgramtab["кс"] = "a,Г,дст,буд,2л,ед";
			rusgramtab["кт"] = "a,Г,дст,буд,2л,мн";
			rusgramtab["ку"] = "a,Г,дст,буд,3л,ед";
			rusgramtab["кф"] = "a,Г,дст,буд,3л,мн";
			rusgramtab["Ръ"] = "a,Г,дст,нст,1л,ед,разг";
			rusgramtab["Ры"] = "a,Г,дст,нст,1л,мн,разг";
			rusgramtab["Рэ"] = "a,Г,дст,нст,2л,ед,разг";
			rusgramtab["Рю"] = "a,Г,дст,нст,2л,мн,разг";
			rusgramtab["Ря"] = "a,Г,дст,нст,3л,ед,разг";
			rusgramtab["кю"] = "a,Г,дст,нст,3л,мн,разг";
			rusgramtab["кя"] = "a,Г,дст,прш,мн,разг";
			rusgramtab["кэ"] = "a,Г,дст,буд,1л,ед,разг";
			rusgramtab["Эа"] = "a,Г,дст,буд,1л,мн,разг";
			rusgramtab["Эб"] = "a,Г,дст,буд,2л,ед,разг";
			rusgramtab["Эв"] = "a,Г,дст,буд,2л,мн,разг";
			rusgramtab["Эг"] = "a,Г,дст,буд,3л,ед,разг";
			rusgramtab["Эд"] = "a,Г,дст,буд,3л,мн,разг";
			rusgramtab["Эе"] = "a,Г,дст,нст,1л,ед,арх";
			rusgramtab["Эж"] = "a,Г,дст,нст,1л,мн,арх";
			rusgramtab["Эз"] = "a,Г,дст,нст,2л,ед,арх";
			rusgramtab["Эи"] = "a,Г,дст,нст,2л,мн,арх";
			rusgramtab["Эй"] = "a,Г,дст,нст,3л,ед,арх";
			rusgramtab["Эк"] = "a,Г,дст,нст,3л,мн,арх";
			rusgramtab["Эл"] = "a,Г,дст,прш,мн,арх";
			rusgramtab["Эм"] = "a,Г,дст,буд,1л,ед,арх";
			rusgramtab["Эн"] = "a,Г,дст,буд,1л,мн,арх";
			rusgramtab["Эо"] = "a,Г,дст,буд,2л,ед,арх";
			rusgramtab["Эп"] = "a,Г,дст,буд,2л,мн,арх";
			rusgramtab["Эр"] = "a,Г,дст,буд,3л,ед,арх";
			rusgramtab["Эс"] = "a,Г,дст,буд,3л,мн,арх";
			rusgramtab["кн"] = "a,ДЕЕПРИЧАСТИЕ,дст,нст";
			rusgramtab["ко"] = "a,ДЕЕПРИЧАСТИЕ,дст,прш";
			rusgramtab["Эт"] = "a,ДЕЕПРИЧАСТИЕ,дст,нст,арх";
			rusgramtab["Эу"] = "a,ДЕЕПРИЧАСТИЕ,дст,прш,арх";
			rusgramtab["нп"] = "a,Г,дст,пвл,1л,мн";
			rusgramtab["къ"] = "a,Г,дст,пвл,1л,ед";
			rusgramtab["кл"] = "a,Г,дст,пвл,2л,ед";
			rusgramtab["км"] = "a,Г,дст,пвл,2л,мн";
			rusgramtab["ль"] = "a,Г,дст,пвл,2л,ед,разг";
			rusgramtab["кь"] = "a,Г,дст,пвл,2л,мн,разг";
			rusgramtab["Эю"] = "a,Г,дст,пвл,2л,ед,аббр,";
			rusgramtab["фъ"] = "a,Г,дст,пвл,2л,ед,арх";
			rusgramtab["фю"] = "a,Г,дст,пвл,2л,мн,арх";
			rusgramtab["ла"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,мр,им";
			rusgramtab["лб"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,мр,рд";
			rusgramtab["лв"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,мр,дт";
			rusgramtab["лг"] = "a,ПРИЧАСТИЕ,од,нст,дст,ед,мр,вн";
			rusgramtab["Ла"] = "a,ПРИЧАСТИЕ,но,нст,дст,ед,мр,вн";
			rusgramtab["лд"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,мр,тв";
			rusgramtab["ле"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,мр,пр";
			rusgramtab["лз"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,им";
			rusgramtab["ли"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,рд";
			rusgramtab["лй"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,дт";
			rusgramtab["лк"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,вн";
			rusgramtab["лл"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,тв";
			rusgramtab["лм"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,жр,пр";
			rusgramtab["ло"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,им";
			rusgramtab["лп"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,рд";
			rusgramtab["лр"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,дт";
			rusgramtab["лс"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,вн";
			rusgramtab["лт"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,тв";
			rusgramtab["лу"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,ед,ср,пр";
			rusgramtab["лх"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,мн,им";
			rusgramtab["лц"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,мн,рд";
			rusgramtab["лч"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,мн,дт";
			rusgramtab["лш"] = "a,ПРИЧАСТИЕ,од,нст,дст,мн,вн";
			rusgramtab["Лй"] = "a,ПРИЧАСТИЕ,но,нст,дст,мн,вн";
			rusgramtab["лщ"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,мн,тв";
			rusgramtab["лы"] = "a,ПРИЧАСТИЕ,од,но,нст,дст,мн,пр";
			rusgramtab["ма"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,мр,им";
			rusgramtab["мб"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,мр,рд";
			rusgramtab["мв"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,мр,дт";
			rusgramtab["мг"] = "a,ПРИЧАСТИЕ,од,прш,дст,ед,мр,вн";
			rusgramtab["Лб"] = "a,ПРИЧАСТИЕ,но,прш,дст,ед,мр,вн";
			rusgramtab["мд"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,мр,тв";
			rusgramtab["ме"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,мр,пр";
			rusgramtab["мз"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,им";
			rusgramtab["ми"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,рд";
			rusgramtab["мй"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,дт";
			rusgramtab["мк"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,вн";
			rusgramtab["мл"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,тв";
			rusgramtab["мм"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,жр,пр";
			rusgramtab["мо"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,им";
			rusgramtab["мп"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,рд";
			rusgramtab["мр"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,дт";
			rusgramtab["мс"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,вн";
			rusgramtab["мт"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,тв";
			rusgramtab["му"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,ед,ср,пр";
			rusgramtab["мх"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,мн,им";
			rusgramtab["мц"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,мн,рд";
			rusgramtab["мч"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,мн,дт";
			rusgramtab["мш"] = "a,ПРИЧАСТИЕ,од,прш,дст,мн,вн";
			rusgramtab["Лк"] = "a,ПРИЧАСТИЕ,но,прш,дст,мн,вн";
			rusgramtab["мщ"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,мн,тв";
			rusgramtab["мы"] = "a,ПРИЧАСТИЕ,од,но,прш,дст,мн,пр";
			rusgramtab["па"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,мр,им";
			rusgramtab["пб"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,мр,рд";
			rusgramtab["пв"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,мр,дт";
			rusgramtab["пг"] = "b,ПРИЧАСТИЕ,од,нст,стр,ед,мр,вн";
			rusgramtab["Лг"] = "b,ПРИЧАСТИЕ,но,нст,стр,ед,мр,вн";
			rusgramtab["пд"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,мр,тв";
			rusgramtab["пе"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,мр,пр";
			rusgramtab["пж"] = "b,КР_ПРИЧАСТИЕ,од,но,нст,стр,ед,мр";
			rusgramtab["пз"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,им";
			rusgramtab["пи"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,рд";
			rusgramtab["пй"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,дт";
			rusgramtab["пк"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,вн";
			rusgramtab["пл"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,тв";
			rusgramtab["пм"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,жр,пр";
			rusgramtab["пн"] = "b,КР_ПРИЧАСТИЕ,од,но,нст,стр,ед,жр";
			rusgramtab["по"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,им";
			rusgramtab["пп"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,рд";
			rusgramtab["пр"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,дт";
			rusgramtab["пс"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,вн";
			rusgramtab["пт"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,тв";
			rusgramtab["пу"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,ед,ср,пр";
			rusgramtab["пф"] = "b,КР_ПРИЧАСТИЕ,од,но,нст,стр,ед,ср";
			rusgramtab["пх"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,мн,им";
			rusgramtab["пц"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,мн,рд";
			rusgramtab["пч"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,мн,дт";
			rusgramtab["пш"] = "b,ПРИЧАСТИЕ,од,нст,стр,мн,вн";
			rusgramtab["Лм"] = "b,ПРИЧАСТИЕ,но,нст,стр,мн,вн";
			rusgramtab["пщ"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,мн,тв";
			rusgramtab["пы"] = "b,ПРИЧАСТИЕ,од,но,нст,стр,мн,пр";
			rusgramtab["пэ"] = "b,КР_ПРИЧАСТИЕ,од,но,нст,стр,мн";
			rusgramtab["са"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,мр,им";
			rusgramtab["сб"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,мр,рд";
			rusgramtab["св"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,мр,дт";
			rusgramtab["сг"] = "b,ПРИЧАСТИЕ,од,прш,стр,ед,мр,вн";
			rusgramtab["Ле"] = "b,ПРИЧАСТИЕ,но,прш,стр,ед,мр,вн";
			rusgramtab["сд"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,мр,тв";
			rusgramtab["се"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,мр,пр";
			rusgramtab["сж"] = "b,КР_ПРИЧАСТИЕ,од,но,прш,стр,ед,мр";
			rusgramtab["сз"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,им";
			rusgramtab["си"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,рд";
			rusgramtab["сй"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,дт";
			rusgramtab["ск"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,вн";
			rusgramtab["сл"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,тв";
			rusgramtab["см"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,жр,пр";
			rusgramtab["сн"] = "b,КР_ПРИЧАСТИЕ,од,но,прш,стр,ед,жр";
			rusgramtab["со"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,им";
			rusgramtab["сп"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,рд";
			rusgramtab["ср"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,дт";
			rusgramtab["сс"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,вн";
			rusgramtab["ст"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,тв";
			rusgramtab["су"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,ед,ср,пр";
			rusgramtab["сф"] = "b,КР_ПРИЧАСТИЕ,од,но,прш,стр,ед,ср";
			rusgramtab["сх"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,мн,им";
			rusgramtab["сц"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,мн,рд";
			rusgramtab["сч"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,мн,дт";
			rusgramtab["сш"] = "b,ПРИЧАСТИЕ,од,прш,стр,мн,вн";
			rusgramtab["Ло"] = "b,ПРИЧАСТИЕ,но,прш,стр,мн,вн";
			rusgramtab["сщ"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,мн,тв";
			rusgramtab["сы"] = "b,ПРИЧАСТИЕ,од,но,прш,стр,мн,пр";
			rusgramtab["сэ"] = "b,КР_ПРИЧАСТИЕ,од,но,прш,стр,мн";
			rusgramtab["ча"] = "e,МС,1л,ед,им";
			rusgramtab["чб"] = "e,МС,1л,ед,рд";
			rusgramtab["чв"] = "e,МС,1л,ед,дт";
			rusgramtab["чг"] = "e,МС,1л,ед,вн";
			rusgramtab["чд"] = "e,МС,1л,ед,тв";
			rusgramtab["че"] = "e,МС,1л,ед,пр";
			rusgramtab["чж"] = "e,МС,1л,мн,им";
			rusgramtab["чз"] = "e,МС,1л,мн,рд";
			rusgramtab["чи"] = "e,МС,1л,мн,дт";
			rusgramtab["чй"] = "e,МС,1л,мн,вн";
			rusgramtab["чк"] = "e,МС,1л,мн,тв";
			rusgramtab["чл"] = "e,МС,1л,мн,пр";
			rusgramtab["чм"] = "e,МС,2л,ед,им";
			rusgramtab["чн"] = "e,МС,2л,ед,рд";
			rusgramtab["чо"] = "e,МС,2л,ед,дт";
			rusgramtab["чп"] = "e,МС,2л,ед,вн";
			rusgramtab["чр"] = "e,МС,2л,ед,тв";
			rusgramtab["чс"] = "e,МС,2л,ед,пр";
			rusgramtab["чт"] = "e,МС,2л,мн,им";
			rusgramtab["чу"] = "e,МС,2л,мн,рд";
			rusgramtab["чф"] = "e,МС,2л,мн,дт";
			rusgramtab["чх"] = "e,МС,2л,мн,вн";
			rusgramtab["чц"] = "e,МС,2л,мн,тв";
			rusgramtab["чч"] = "e,МС,2л,мн,пр";
			rusgramtab["ша"] = "e,МС,3л,мр,ед,им";
			rusgramtab["шб"] = "e,МС,3л,мр,ед,рд";
			rusgramtab["шв"] = "e,МС,3л,мр,ед,дт";
			rusgramtab["шг"] = "e,МС,3л,мр,ед,вн";
			rusgramtab["шд"] = "e,МС,3л,мр,ед,тв";
			rusgramtab["ше"] = "e,МС,3л,мр,ед,пр";
			rusgramtab["шж"] = "e,МС,3л,жр,ед,им";
			rusgramtab["шз"] = "e,МС,3л,жр,ед,рд";
			rusgramtab["ши"] = "e,МС,3л,жр,ед,дт";
			rusgramtab["шй"] = "e,МС,3л,жр,ед,вн";
			rusgramtab["шк"] = "e,МС,3л,жр,ед,тв";
			rusgramtab["шл"] = "e,МС,3л,жр,ед,пр";
			rusgramtab["шм"] = "e,МС,3л,ср,ед,им";
			rusgramtab["шн"] = "e,МС,3л,ср,ед,рд";
			rusgramtab["шо"] = "e,МС,3л,ср,ед,дт";
			rusgramtab["шп"] = "e,МС,3л,ср,ед,вн";
			rusgramtab["шр"] = "e,МС,3л,ср,ед,тв";
			rusgramtab["шс"] = "e,МС,3л,ср,ед,пр";
			rusgramtab["шт"] = "e,МС,3л,мн,им";
			rusgramtab["шу"] = "e,МС,3л,мн,рд";
			rusgramtab["шф"] = "e,МС,3л,мн,дт";
			rusgramtab["шх"] = "e,МС,3л,мн,вн";
			rusgramtab["шц"] = "e,МС,3л,мн,тв";
			rusgramtab["шч"] = "e,МС,3л,мн,пр";
			rusgramtab["ща"] = "e,МС,мр,ед,им";
			rusgramtab["щб"] = "e,МС,мр,ед,рд";
			rusgramtab["щв"] = "e,МС,мр,ед,дт";
			rusgramtab["щг"] = "e,МС,мр,ед,вн";
			rusgramtab["щд"] = "e,МС,мр,ед,тв";
			rusgramtab["ще"] = "e,МС,мр,ед,пр";
			rusgramtab["щж"] = "e,МС,жр,ед,им";
			rusgramtab["щз"] = "e,МС,жр,ед,рд";
			rusgramtab["щи"] = "e,МС,жр,ед,дт";
			rusgramtab["щй"] = "e,МС,жр,ед,вн";
			rusgramtab["щк"] = "e,МС,жр,ед,тв";
			rusgramtab["щл"] = "e,МС,жр,ед,пр";
			rusgramtab["щм"] = "e,МС,ср,ед,им";
			rusgramtab["щн"] = "e,МС,ср,ед,рд";
			rusgramtab["що"] = "e,МС,ср,ед,дт";
			rusgramtab["щп"] = "e,МС,ср,ед,вн";
			rusgramtab["щр"] = "e,МС,ср,ед,тв";
			rusgramtab["щс"] = "e,МС,ср,ед,пр";
			rusgramtab["щт"] = "e,МС,мн,им";
			rusgramtab["щу"] = "e,МС,мн,рд";
			rusgramtab["щф"] = "e,МС,мн,дт";
			rusgramtab["щх"] = "e,МС,мн,вн";
			rusgramtab["щц"] = "e,МС,мн,тв";
			rusgramtab["щч"] = "e,МС,мн,пр";
			rusgramtab["щщ"] = "e,МС,рд";
			rusgramtab["щы"] = "e,МС,дт";
			rusgramtab["щэ"] = "e,МС,вн";
			rusgramtab["щю"] = "e,МС,тв";
			rusgramtab["щя"] = "e,МС,пр";
			rusgramtab["ыа"] = "f,МС-П,мр,ед,им,од,но";
			rusgramtab["ыб"] = "f,МС-П,мр,ед,рд,од,но";
			rusgramtab["ыв"] = "f,МС-П,мр,ед,дт,од,но";
			rusgramtab["ыг"] = "f,МС-П,мр,ед,вн,но";
			rusgramtab["Лф"] = "f,МС-П,мр,ед,вн,од";
			rusgramtab["ыд"] = "f,МС-П,мр,ед,тв,од,но";
			rusgramtab["ые"] = "f,МС-П,мр,ед,пр,од,но";
			rusgramtab["ыж"] = "f,МС-П,жр,ед,им,од,но";
			rusgramtab["ыз"] = "f,МС-П,жр,ед,рд,од,но";
			rusgramtab["ыи"] = "f,МС-П,жр,ед,дт,од,но";
			rusgramtab["ый"] = "f,МС-П,жр,ед,вн,од,но";
			rusgramtab["ык"] = "f,МС-П,жр,ед,тв,од,но";
			rusgramtab["ыл"] = "f,МС-П,жр,ед,пр,од,но";
			rusgramtab["ым"] = "f,МС-П,ср,ед,им,од,но";
			rusgramtab["ын"] = "f,МС-П,ср,ед,рд,од,но";
			rusgramtab["ыо"] = "f,МС-П,ср,ед,дт,од,но";
			rusgramtab["ып"] = "f,МС-П,ср,ед,вн,од,но";
			rusgramtab["ыр"] = "f,МС-П,ср,ед,тв,од,но";
			rusgramtab["ыс"] = "f,МС-П,ср,ед,пр,од,но";
			rusgramtab["ыт"] = "f,МС-П,мн,им,од,но";
			rusgramtab["ыу"] = "f,МС-П,мн,рд,од,но";
			rusgramtab["ыф"] = "f,МС-П,мн,дт,од,но";
			rusgramtab["ых"] = "f,МС-П,мн,вн,но";
			rusgramtab["Лх"] = "f,МС-П,мн,вн,од";
			rusgramtab["ыц"] = "f,МС-П,мн,тв,од,но";
			rusgramtab["ыч"] = "f,МС-П,мн,пр,од,но";
			rusgramtab["ыш"] = "f,МС-П,0,од,но";
			rusgramtab["ыщ"] = "g,МС-ПРЕДК,ед,рд";
			rusgramtab["ыы"] = "g,МС-ПРЕДК,ед,дт";
			rusgramtab["ыэ"] = "g,МС-ПРЕДК,ед,вн";
			rusgramtab["ыю"] = "g,МС-ПРЕДК,ед,тв";
			rusgramtab["ыь"] = "g,МС-ПРЕДК,ед,пр";
			rusgramtab["ыя"] = "g,МС-ПРЕДК";
			rusgramtab["эа"] = "h,ЧИСЛ,им";
			rusgramtab["эб"] = "h,ЧИСЛ,рд";
			rusgramtab["эв"] = "h,ЧИСЛ,дт";
			rusgramtab["эг"] = "h,ЧИСЛ,вн";
			rusgramtab["эд"] = "h,ЧИСЛ,тв";
			rusgramtab["эе"] = "h,ЧИСЛ,пр";
			rusgramtab["Ца"] = "h,ЧИСЛ,им,арх";
			rusgramtab["Цб"] = "h,ЧИСЛ,рд,арх";
			rusgramtab["Цв"] = "h,ЧИСЛ,дт,арх";
			rusgramtab["Цг"] = "h,ЧИСЛ,вн,арх";
			rusgramtab["Цд"] = "h,ЧИСЛ,тв,арх";
			rusgramtab["Це"] = "h,ЧИСЛ,пр,арх";
			rusgramtab["эж"] = "h,ЧИСЛ,мр,им";
			rusgramtab["эз"] = "h,ЧИСЛ,мр,рд";
			rusgramtab["эи"] = "h,ЧИСЛ,мр,дт";
			rusgramtab["эй"] = "h,ЧИСЛ,мр,вн";
			rusgramtab["эк"] = "h,ЧИСЛ,мр,тв";
			rusgramtab["эл"] = "h,ЧИСЛ,мр,пр";
			rusgramtab["эм"] = "h,ЧИСЛ,жр,им";
			rusgramtab["эн"] = "h,ЧИСЛ,жр,рд";
			rusgramtab["эо"] = "h,ЧИСЛ,жр,дт";
			rusgramtab["эп"] = "h,ЧИСЛ,жр,вн";
			rusgramtab["эр"] = "h,ЧИСЛ,жр,тв";
			rusgramtab["эс"] = "h,ЧИСЛ,жр,пр";
			rusgramtab["эт"] = "h,ЧИСЛ,ср,им";
			rusgramtab["эу"] = "h,ЧИСЛ,ср,рд";
			rusgramtab["эф"] = "h,ЧИСЛ,ср,дт";
			rusgramtab["эх"] = "h,ЧИСЛ,ср,вн";
			rusgramtab["эц"] = "h,ЧИСЛ,ср,тв";
			rusgramtab["эч"] = "h,ЧИСЛ,ср,пр";
			rusgramtab["эш"] = "h,ЧИСЛ,сравн";
			rusgramtab["юа"] = "i,ЧИСЛ-П,мр,ед,им,од,но";
			rusgramtab["юб"] = "i,ЧИСЛ-П,мр,ед,рд,од,но";
			rusgramtab["юв"] = "i,ЧИСЛ-П,мр,ед,дт,од,но";
			rusgramtab["юг"] = "i,ЧИСЛ-П,мр,ед,вн,но";
			rusgramtab["Лт"] = "i,ЧИСЛ-П,мр,ед,вн,од";
			rusgramtab["юд"] = "i,ЧИСЛ-П,мр,ед,тв,од,но";
			rusgramtab["юе"] = "i,ЧИСЛ-П,мр,ед,пр,од,но";
			rusgramtab["юж"] = "i,ЧИСЛ-П,жр,ед,им,од,но";
			rusgramtab["юз"] = "i,ЧИСЛ-П,жр,ед,рд,од,но";
			rusgramtab["юи"] = "i,ЧИСЛ-П,жр,ед,дт,од,но";
			rusgramtab["юй"] = "i,ЧИСЛ-П,жр,ед,вн,од,но";
			rusgramtab["юк"] = "i,ЧИСЛ-П,жр,ед,тв,од,но";
			rusgramtab["юл"] = "i,ЧИСЛ-П,жр,ед,пр,од,но";
			rusgramtab["юм"] = "i,ЧИСЛ-П,ср,ед,им,од,но";
			rusgramtab["юн"] = "i,ЧИСЛ-П,ср,ед,рд,од,но";
			rusgramtab["юо"] = "i,ЧИСЛ-П,ср,ед,дт,од,но";
			rusgramtab["юп"] = "i,ЧИСЛ-П,ср,ед,вн,од,но";
			rusgramtab["юр"] = "i,ЧИСЛ-П,ср,ед,тв,од,но";
			rusgramtab["юс"] = "i,ЧИСЛ-П,ср,ед,пр,од,но";
			rusgramtab["ют"] = "i,ЧИСЛ-П,мн,им,од,но";
			rusgramtab["юу"] = "i,ЧИСЛ-П,мн,рд,од,но";
			rusgramtab["юф"] = "i,ЧИСЛ-П,мн,дт,од,но";
			rusgramtab["юх"] = "i,ЧИСЛ-П,мн,вн,но";
			rusgramtab["Лу"] = "i,ЧИСЛ-П,мн,вн,од";
			rusgramtab["юц"] = "i,ЧИСЛ-П,мн,тв,од,но";
			rusgramtab["юч"] = "i,ЧИСЛ-П,мн,пр,од,но";
			rusgramtab["ющ"] = "i,ЧИСЛ-П,рд,од,но";
			rusgramtab["яа"] = "j,Н";
			rusgramtab["ян"] = "j,Н,вопр";
			rusgramtab["яо"] = "j,Н,указат";
			rusgramtab["яп"] = "j,Н,разг";
			rusgramtab["яб"] = "k,ПРЕДК,нст";
			rusgramtab["як"] = "k,ПРЕДК,прш";
			rusgramtab["ял"] = "k,ПРЕДК,";
			rusgramtab["яр"] = "k,ПРЕДК,сравн,нст";
			rusgramtab["ям"] = "k,ПРЕДК,0";
			rusgramtab["яв"] = "l,ПРЕДЛ";
			rusgramtab["яг"] = "m,ПОСЛ";
			rusgramtab["яд"] = "n,СОЮЗ";
			rusgramtab["яе"] = "o,МЕЖД";
			rusgramtab["яё"] = "o,МЕЖД,разг";
			rusgramtab["яж"] = "p,ЧАСТ";
			rusgramtab["яз"] = "q,ВВОДН";
			rusgramtab["яй"] = "s,ФРАЗ";
			rusgramtab["Пп"] = "b,Г,стр,буд,1л,ед";
			rusgramtab["Пр"] = "b,Г,стр,буд,1л,мн";
			rusgramtab["Пс"] = "b,Г,стр,буд,2л,ед";
			rusgramtab["Пт"] = "b,Г,стр,буд,2л,мн";
			rusgramtab["Пу"] = "b,Г,стр,буд,3л,ед";
			rusgramtab["Пф"] = "b,Г,стр,буд,3л,мн";
			rusgramtab["Уа"] = "a,*,лок";
			rusgramtab["Уе"] = "a,*,кач";
			rusgramtab["Уж"] = "a,*,дфст";
			rusgramtab["Уз"] = "a,*,дфст,орг";
			rusgramtab["Уи"] = "a,*,дфст,лок";
			rusgramtab["Ул"] = "a,*,св,пе";
			rusgramtab["Ум"] = "a,*,св,нп";
			rusgramtab["Ун"] = "a,*,нс,пе";
			rusgramtab["Уо"] = "a,*,нс,нп";
			rusgramtab["Уп"] = "a,*,св,нс,пе";
			rusgramtab["Ур"] = "a,*,св,нс,нп";
			rusgramtab["Ус"] = "a,*,нс";
			rusgramtab["Ут"] = "a,*,св";
			rusgramtab["Уф"] = "a,*,жарг";
			rusgramtab["Ух"] = "a,*,опч";
			rusgramtab["Уч"] = "a,*,жарг,опч";
			rusgramtab["Уц"] = "a,*,орг,жарг";
			rusgramtab["Уш"] = "a,*,лок,жарг";
			rusgramtab["Ущ"] = "a,*,но,лок";
			rusgramtab["Уь"] = "a,*,но,орг";
			rusgramtab["Уы"] = "a,*,од,фам";
			rusgramtab["Уъ"] = "a,*,но,дфст,лок";
			rusgramtab["Уэ"] = "a,*,но,дфст,орг";
			rusgramtab["Ую"] = "a,*,но,жарг";
			rusgramtab["Уя"] = "a,*,но,опч,";
			rusgramtab["Фа"] = "a,*,но,";
			rusgramtab["Фб"] = "a,*,од,";
			rusgramtab["Фв"] = "a,*,орг,жарг,но";
			rusgramtab["Фг"] = "a,*,дфст,но";
			rusgramtab["Фд"] = "a,*,дфст,од";
			rusgramtab["Фж"] = "a,*,од,жарг";
			rusgramtab["Фз"] = "a,*,имя,притяж";
			rusgramtab["Фи"] = "a,*,притяж";
			rusgramtab["Фк"] = "a,*,св,пе,разг";
			rusgramtab["Фл"] = "a,*,св,нп,разг";
			rusgramtab["Фн"] = "a,*,нс,пе,разг";
			rusgramtab["Фо"] = "a,*,нс,нп,разг";
			rusgramtab["Фп"] = "a,*,но,разг";
			rusgramtab["Фр"] = "a,*,од,разг";
			rusgramtab["Фс"] = "a,*,св,пе,жарг";
			rusgramtab["Фт"] = "a,*,св,нп,жарг";
			rusgramtab["Фу"] = "a,*,нс,пе,жарг";
			rusgramtab["Фф"] = "a,*,нс,нп,жарг";
			rusgramtab["Фх"] = "a,*,разг";
			rusgramtab["Фц"] = "a,*,арх";
			rusgramtab["Фч"] = "a,*,св,пе,арх";
			rusgramtab["Фш"] = "a,*,св,нп,арх";
			rusgramtab["Фщ"] = "a,*,нс,пе,арх";
			rusgramtab["Фь"] = "a,*,нс,нп,арх";
			rusgramtab["Фы"] = "a,*,но,арх";
			rusgramtab["Фъ"] = "a,*,од,арх";
			rusgramtab["Фэ"] = "a,*,нс,арх";
			rusgramtab["Фю"] = "a,*,св,арх";
			rusgramtab["Фя"] = "a,*,кач,арх";
			rusgramtab["Фё"] = "a,*,но,од";
			rusgramtab["Ха"] = "a,*,од,опч,";
			rusgramtab["Хб"] = "a,*,лок,опч,";
			rusgramtab["яю"] = "F,С,мр,жр,ср,ед,им,рд,дт,вн,тв,пр";
			rusgramtab["яя"] = "F,С,мр,жр,ср,,ед,мн,им,рд,дт,вн,тв,пр";
		}

	}
}
